/*    Ricardo Garriga-Ramos
*/
-- Employees
INSERT INTO employees VALUES ('luke', 'longhands', 'longhands@gmail.com', '1988-11-12', '2009-09-14', null, false);
INSERT INTO employees VALUES ('joe', 'bob', 'joebob@gmail.com', '1999-01-01', '2020-12-20', 002, false);
INSERT INTO employees VALUES ('ricardo', 'garriga', 'garrigaR@gmail.com', '2002-09-11', '2023-04-03', 002, true);
INSERT INTO employees VALUES ('spider', 'man', 'spiderman@gmail.com', '0001-01-01', '2023-04-03', 002, false);
INSERT INTO employees VALUES ('luka', 'tim', 'lucastimothy@gmail.com', '2023-01-07', '2023-03-17', 002, false);
INSERT INTO employees VALUES ('imap', 'smith', 'imapsmith@gmail.com', '1990-07-22', '2016-05-11', 005, false);

-- Admins
INSERT INTO admins VALUES ();
INSERT INTO admins VALUES ();
INSERT INTO admins VALUES ();

-- Users
INSERT INTO users VALUES ('mikespammer', 'passwordenjoyer123', '2013-06-20', false, false);
INSERT INTO users VALUES ('chetlemon', 'Lw3naw5p', '2010-11-11', true, false);
INSERT INTO users VALUES ('Alfred Pennyworth', 'Batman', '2022-04-19', false, false);
INSERT INTO users VALUES ('chemtinehazwick', 'pasward123', '2018-04-29', true, false);
INSERT INTO users VALUES ('arriath', 'a78udl4aw', '2015-08-04', true, false);

-- Platform_bans
INSERT INTO platform_bans VALUES ('spam', '2023-01-17 12:33:17', false);
INSERT INTO platform_bans VALUES ('botting', '2023-02-26 08:09:37', true);

-- Programmers
INSERT INTO programmers VALUES ('database man',null);
INSERT INTO programmers VALUES ('database eng',null);
INSERT INTO programmers VALUES ('AI',null);
INSERT INTO programmers VALUES ('Java boy',null);

-- Projects
INSERT INTO projects VALUES ('schema and instance', '2015-03-19', 'https://github.com/apple/ml-stable-diffusion', null);
INSERT INTO projects VALUES ('auto-GPT', '2020-08-25','https://github.com/Torantulino/Auto-GPT', null);

UPDATE programmers
SET project_id = 101
WHERE programmer_id = 111 or programmer_id = 112;
UPDATE programmers
SET project_id = 102
WHERE programmer_id = 113 or programmer_id = 114;
UPDATE projects
SET project_lead = 111
WHERE project_id = 113 or project_id = 101;
UPDATE projects
SET project_lead = 113
WHERE project_id = 113 or project_id = 102;

-- Platforms
INSERT INTO platforms VALUES ('01userxX', 'hardpassword');
INSERT INTO platforms VALUES ('iminyourwalls', 'nio2c2elj');
INSERT INTO platforms VALUES ('chemtinehazwick', 'pasward123');
INSERT INTO platforms VALUES ('mikespammer', 'passwordenjoyer123');
INSERT INTO platforms VALUES ('iminyourwalls', 'mlk5awp6ti9d');
INSERT INTO platforms VALUES ('Alfred Pennyworth', 'Batman');
INSERT INTO platforms VALUES ('chemtinehazwick', 'realautogeneratedpassword');

-- Creators
INSERT INTO creators VALUES ();
INSERT INTO creators VALUES ();
INSERT INTO creators VALUES ();

-- Chatrooms
INSERT INTO chatrooms VALUES ('mikespammers chat');
INSERT INTO chatrooms VALUES ('chetlemons chat');
INSERT INTO chatrooms VALUES ('chemtinehazwicks chat');

-- Moderators
INSERT INTO moderators VALUES ();
INSERT INTO moderators VALUES ();
INSERT INTO moderators VALUES ();
INSERT INTO moderators VALUES ();
INSERT INTO moderators VALUES ();
INSERT INTO moderators VALUES ();

-- Chatroom_bans
INSERT INTO chatroom_bans VALUES (null, '2009-06-12 10:44:43', true);
INSERT INTO chatroom_bans VALUES (null, '2011-12-25 08:28:07', false);
INSERT INTO chatroom_bans VALUES (null, '2009-12-10 11:21:08', false);
INSERT INTO chatroom_bans VALUES ('vengence', '2010-11-15 07:48:04', false);

-- Chats
INSERT INTO chats VALUES ( '2009-12-10 08:59:53','https://www.youtube.com/watch?v=dQw4w9WgXcQ');

-- Followers
INSERT INTO followers VALUES (241,201,212);


-- Content
INSERT INTO content VALUES ('video','randomURL',211);
INSERT INTO content VALUES ('image','myURL',211);
INSERT INTO content VALUES (243,'video','URL.com',211);
INSERT INTO content VALUES (244,'video','contentURL',212);
INSERT INTO content VALUES (245,'writing','maifesto',211);

-- Mercandise
INSERT INTO mercandise VALUES ('hat',21.99,10,3,7,211);
INSERT INTO mercandise VALUES ('cup',30.98,6,2,4,211);

-- Mercandise_receipts
INSERT INTO mercandise_receipts VALUES (251,205,'2018-11-21','4 Privet Drive, Little Whinging, Surrey');
INSERT INTO mercandise_receipts VALUES (251,204,'2012-01-13','124 Conch Street, Bikini Bottom, Pacific Ocean');
INSERT INTO mercandise_receipts VALUES (252,205,'2012-06-15','4 Privet Drive, Little Whinging, Surrey');
INSERT INTO mercandise_receipts VALUES (251,202,'2010-06-27','301 Cobblestone Way, Bedrock, 70777');
INSERT INTO mercandise_receipts VALUES (252,202,'2015-05-07','301 Cobblestone Way, Bedrock, 70777');

-- Subscriptions
INSERT INTO subscriptions VALUES (261,211,null,5.00, null);
INSERT INTO subscriptions VALUES (262,212,null,10.00, null);
INSERT INTO subscriptions VALUES (263,213,'monthly art',20.00, null);

-- Subscription_reciepts
INSERT INTO subscription_reciepts VALUES (261,202,'2018-03-28',null);
INSERT INTO subscription_reciepts VALUES (261,203,'2019-06-11',null);
INSERT INTO subscription_reciepts VALUES (262,201,'2017-08-20',null);
INSERT INTO subscription_reciepts VALUES (263,205,'2021-01-03',null);